---
title: Zwermen, scholen en kuddes
hero_image: images/banner.png
description: Maak een spel dat klonen gebruikt om zwermen, scholen, kuddes of een andere groep dieren te maken.
meta_title: Scratch-programmeerprojecten voor kinderen en tieners | Zwermen en kuddes
meta_description: Leer Scratch met de programmeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Maak een spelletje met Scratch dat klonen gebruikt om groepen dieren te maken.
version: 4
listed: true
copyedit: true
last_tested: '2021-06-02'
steps:
  - title: Wat ga je maken
  - title: Maak je bewegende scène
  - title: Voeg je klonen toe
    completion:
      - engaged
  - title: Voer je klonen
  - title: Voeg een roofdier toe
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project
  - title: Deel
  - title: Wat kun je verder nog doen?
