title: swarms-schools-flocks
hero_image: images/banner.png
description: swarms-schools-flocks description
version: 4
listed: false
copyedit: false
last_tested: "2021-06-02"
steps:
  - title: Introduction
  - title: Create the creatures
  - title: What next?
