title: swarms-schools-flocks
hero_image: images/banner.png
description: swarms-schools-flocks description
version: 4
listed: false
copyedit: false
last_tested: "2021-06-02"
steps:
  - title: Introduction
  - title: Create your scrolling scene
  - title: Add your clones
  - title: Feed your clones
  - title: Add a predator
  - title: Reflection
  - title: Upgrade your project
  - title: Share
  - title: "What next?"